apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Secret
metadata:
  name: playwright-env
  namespace: monitoring
type: Opaque
data: # base64 encoded values
  MAIL_RECEIVERS: 
  MAIL_SENDER: 
  MAIL_SENDER_PASSWORD: 
  TELEGRAM_BOT_TOKEN: 
  TELEGRAM_CHAT_ID: 
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: playwright-test
  namespace: monitoring
spec:
  schedule: "*/5 * * * *"  # each 5 minutes
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
            - name: playwright
              image: phamtranlinhchi/playwright-test:latest
              command: ["npx", "playwright", "test"]
              envFrom:
                - secretRef:
                    name: playwright-env
          restartPolicy: OnFailure